config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member, as: :publish
      put 'unpublish' => 'posts#unpublish', on: :member, as: :unpublish
    end
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def display_error_messages

  end
  	
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :bigint(8)        not null, primary key
#  first_name             :string
#  last_name              :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates_presence_of :first_name, on: :update

  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end
  
  def display_name
    if first_name.present?
      first_name
    else
      "Author"
    end
  end
end  

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord
  acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author
  has_many :comments

  PER_PAGE = 6

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  
  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not published yet"
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  layout 'author'

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :bio) }
      end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def new
      
    end

    def edit

    end

    def update_info  
      if current_author.update(author_info_params)
        flash[:success] = "Successfully saved info."
      else
      	flash[:danger] = current_author.errors.full_messages.join('. ') << '.'
      end
      redirect_to authors_account_path   
    end

    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password.'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current password was incorrect.'
      end
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:first_name, :last_name, :email, :bio)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end

  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end

end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController
    
    def about
    end
  
    def contact
    end
  
  end  
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end
  end
end 

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/accounts/edit.html.erb
<div class="row">
  <!-- Basic info section -->
  <%= form_tag authors_info_path, method: :put do %>
    <%= fields_for :author do |f| %>
      <div class="col">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
              Basic info
            </div>
          </div>
          <ul class="list-group list-group-flush">    
            <li class="list-group-item">
              <div class="field">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, value: current_author.first_name, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, value: current_author.last_name, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :email %>
                <%= f.text_field :email, value: current_author.email, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :bio %>
                <%= f.text_area :bio, value: current_author.bio, class: 'form-control', size: "40x5" %>
              </div>
            </li>
            <li class='list-group-item'>
              <%= f.submit "Update info", class: 'btn btn-primary' %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
  <!-- Change password section -->
  <%= form_tag authors_change_password_path, method: :put do %>
    <%= fields_for :author do |f| %>
      <div class="col">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
              Change password
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= f.label :current_password %>
                <%= f.password_field :current_password, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :new_password %>
                <%= f.password_field :new_password, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :new_password_confirmation %>
                <%= f.password_field :new_password_confirmation, class: 'form-control' %>
              </div>
            </li>
            <li class='list-group-item'>
              <%= f.submit "Change password", class: 'btn btn-warning' %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true, url: url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">

      <div class="card">
        <div class="card-block">
          <% if @post.new_record? %>
          <h4 class="card-title">Nouvel article</h4>
        <% else %>
        <h4 class="card-title">
        <b>Edit</b>
        <span class="thin-text"><%= @post.title %></span> 
        </h4>
        <% end %> 
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, class: "form-control" %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
            <%= form.label :banner_image_url %>
            <%= form.text_field :banner_image_url, class: "form-control" %>
          </div>
        </li>
        <li class="list-group-item">
          <div class="field">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control" %>
          </div>  
          </li>
           <li class="list-group-item">
            <div class="field">
              <%= form.label 'Tags' %>
              <%= form.text_area :tag_list, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
              <div class="actions">
                <%= form.submit "Save post", class: 'btn btn-success btn-block' %>
              </div>  
            </li>    
          </ul>   
        </div>    
        <% if @post.persisted? %>
          <%= link_to 'Show', @post %>
        <% end %>  
        <%= link_to 'Back', authors_posts_path %>
      </div>
      <div class="col-md-9">
      <div class="field">
        <%= form.text_area :body %>
      </div>
    </div>
  </div>

  
<% end %>

app/views/authors/posts/_post.html.erb
<tr class="smaller-btns">
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td></td>
  <% if post.published? %>
  	<td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
  	<td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>

<div class="row">
  <div style="margin-bottom: 20px;">
    <%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <br>
  <table class="table table-striped">
    <tr>
      <th colspan="5">Title</th>
    </tr>
    <%= render @posts %>
  </table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div class="smaller-btns text-center" style="margin-bottom: 50px;">
  <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:page_title, 'About us') %>
<% provide(:about_active, 'active') %>


 <div id="about" style="padding:20px 20px 0 20px; text-align: center; margin-top: 50px;">
    <h1>About our team</h1>
</div>

<div class="row justify-content-center about-card">
  <div class="col-lg-4 col-sm-12">
    <div class="card">
      <div class="crop">
        <%= image_tag("pic.jpg", alt: "Profile picture") %>
      </div>
      <h2>Nikita Vasilev</h2>
      <p class="title">Full Stack Developer</p>
      <p>Session 6<br>The Hacking Project</p>
      <div class="icons">
        <a href="https://www.linkedin.com/in/nikita-vasilev-2b0112111/"><i class="fab fa-github"></i></a>
        <a href="https://github.com/nikitavasilev"><i class="fab fa-linkedin-in"></i></a>
      </div>
      <p><button><a href="mailto:vassilev.nikita@gmail.com"
        style="color: #fff; font-size: 18px;">Contact</a></button></p> 
    </div>
  </div>
  <div class="col-lg-4 col-sm-12">
    <div class="card">
      <div class="crop">
        <%= image_tag("nat.jpg", alt: "Profile picture") %>
      </div>
      <h2>Nathaniel Debache</h2>
      <p class="title">Full Stack Developer</p>
      <p>Session 6<br>The Hacking Project</p>
      <div class="icons">
        <a href="https://www.linkedin.com/in/nathaniel-debache-06714159//"><i class="fab fa-github"></i></a>
        <a href="https://github.com/Natdenice"><i class="fab fa-linkedin-in"></i></a>
      </div>
      <p><button><a href="mailto:Nathaniel.debache@gmail.com"
        style="color: #fff; font-size: 18px;">Contact</a></button></p> 
    </div>
  </div>
</div>

app/views/blog/pages/contact.html.erb
<% provide(:page_title, 'Contact us') %>
<% provide(:contact_active, 'active') %>

<!-- Contact -->
<section id="contact">
  <div class="container">
    <div class="row" style="margin-bottom: 50px;">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Contact Us</h2>
        <h3 class="section-subheading text-muted">We will get back to you as soon as possible.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form id="contactForm" name="sentMessage" novalidate="novalidate">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input class="form-control" id="name" type="text" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input class="form-control" id="email" type="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input class="form-control" id="phone" type="tel" placeholder="Your Phone" required="required" data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <textarea class="form-control" id="message" placeholder="Your Message" required="required" data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 text-center">
              <div id="success"></div>
              <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section> 

app/views/blog/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= link_to post do %>
      <div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'></div>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to truncate(post.title, length: 25), post, title: post.title %></h4>
      <p class='tags'><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %></p>
      <h6 class="published-date"><%= post.display_day_published %></h6>
      <%= link_to post do %>
        <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <%= render @posts %>
</div>

<div class="pag">
  <% if @posts.length > 0 && @posts.total_pages > 1 %>
    <div class="apple_pagination">
      <%= will_paginate @posts, container: false %>
    </div>
  <% end %>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row d-flex justify-content-center">
  <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <h6><%= @post.display_day_published %></h6>
    <%= @post.body.html_safe %>

    <div class="author-bio">
      <h4><%= @post.author.first_name %> <%= @post.author.last_name %></h4>
      <h6 class="bio"><%= @post.author.bio %></h6>
    </div>  	

    <div id="disqus_thread"></div>
    <noscript>
      Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>	
    </noscript>
  </div>
</div>

<script>
  /*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

  var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://blog-nicois.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
</script>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer id="footer-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Made with <i class="fas fa-heart"></i> by <a href="https://github.com/Natdenice">Nathaniel D.</a> & <a href="https://github.com/nikitavasilev">Nikita V.</a></span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://twitter.com/stackoverflow">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.facebook.com/officialstackoverflow/">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.linkedin.com/company/stack-overflow/">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li class="list-inline-item">
            <a href="#">Privacy Policy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
      <i class="fab fa-stack-overflow fa-2x"></i>
    <a class="navbar-brand js-scroll-trigger" href="/" style="padding-left: 10px;">stack<strong>overnice</strong></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if !(author_signed_in?) %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_author_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_author_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if author_signed_in? %>
          <li class="nav-item dropdown author-nav">
            <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_author.display_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'My posts', authors_posts_path, class: "dropdown-item #{yield(:author)}" %>
              <%= link_to 'Account', authors_account_path, class: "dropdown-item" %>
              <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Stack Overnice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('stack-overflow.png') %>
    <script src="https://devpreview.tiny.cloud/demo/tinymce.min.js"></script>
  </head>

  <body id="page-top">
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">

      <% if flash.any? %>
        <% flash.keys.each do |key| %>
          <div class="alert alert-<%= key.to_s %> alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[key] %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Stack Overnice</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('stack-overflow.png') %>
  </head>

  <body id="page-top">
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>